### ISSUE TITLE
document required

### ISSUE THREAD

**Issue by dongfo** [AvaloniaUI/Wordle-onia#5]
It is nice to see that avalonia supports  to create examples in one project which can run on multiple platforms. However, we need to refer to the documentation to run and debug this project, can you provide the documentation?

**Comment by Glacial** [comment]
I can't get this running on iOS. With this source I can't deploy to the simulator or device as I get a "Failed to install" error in Rider. Grepping the logs in more detail the error reads "Failed to find matching arch for input file: [...]/Wordle.iOS.app/Wordle.iOS".
Documentation on how to build and run this would be a great help.

**Comment by danwalmsley** [comment]
https://docs.avaloniaui.net/tutorials/developing-for-mobile

**Comment by danwalmsley** [comment]
if those dont work please open another issue.
