### ISSUE TITLE
Sigh. Why does this not "just work" ?

### ISSUE THREAD

**Issue by Resonanz** [AvaloniaUI/Wordle-onia#6]
Downloaded with Github desktop to Windows 10.

Opened the project and pressed the run button.

![image](https://user-images.githubusercontent.com/6218191/220520742-7ec09366-5561-4533-a514-df94b8e4158e.png)

**Comment by maxkatz6** [comment]
Because you are trying to run a shared class library and not executable project. You need to run [Wordle.Desktop](https://github.com/AvaloniaUI/Wordle-onia/tree/main/Wordle.Desktop) on desktop (win, mac, lin).
